create table TBL_ITEMS (
	item_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 11, INCREMENT BY 1),
	ownerID INTEGER,
	title VARCHAR(30),
	category VARCHAR(30),
	picture VARCHAR(200),
	description VARCHAR(200),
	address VARCHAR(100),
	reservePrice FLOAT,
	startPrice FLOAT,
	bidIncrements FLOAT,
	endTime TIMESTAMP,
	highestBid FLOAT,
	highest_bid_user_ID INT,
	isActive BOOLEAN,
	bidAccepted INT,
	CONSTRAINT pk_items PRIMARY KEY (item_id)
);

drop table TBL_ITEMS;