CREATE TABLE TBL_USERS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 5, INCREMENT BY 1),
    username VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    nickname VARCHAR(20),
    firstname VARCHAR(20),
    lastname VARCHAR(20),
	date_of_birth VARCHAR(10),
	street_address VARCHAR(100),
	city VARCHAR(50),
	state VARCHAR(50),
	country VARCHAR(50),
	postcode INTEGER,
	credit_card_number INTEGER,
	account_state INTEGER NOT NULL,
	admin BOOLEAN NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (id)
);

DROP table tbl_users;